In [2]:
# 1. 数组的创建

# 导入numpy包
import numpy as np
# 使用np.array()函数从已有list创建ndarray
nums = np.array([[1, 2, 3], [4, 5, 6]])

print(nums)        # 输出创建好的多维数组
print(nums.dtype)  # 查看数组元素类型
print(nums.shape)  # 查看数组的尺寸
print(nums.ndim)   # 查看数组的纬度

[[1 2 3]
 [4 5 6]]
int64
(2, 3)
2


In [3]:
# 创建一个空数组并赋值
# 使用np.empty()函数创建一个空数组，第一个参数指定数组的形状，第二个参数指定数组元素的类型
nines = np.empty((3, 3), np.int)
nines[:] = 9  # 这种写法后面切片部分介绍
print(nines)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [7]:
# 使用range创建一个列表，然后将列表中的元素进行reshape改变形状
nums = np.reshape(range(16), (4, 4))
print(nums)

# 对该多维数组进行转置
nums = np.transpose(nums)
print(nums)

# 再次进行reshape
print(np.reshape(nums, (2, 4, 2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[[ 0  4]
  [ 8 12]
  [ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]
  [ 3  7]
  [11 15]]]


In [21]:
# 2. 索引和切片

import numpy as np
nums = np.arange(12).reshape(4, 3);
print(nums)
# 访问第一行元素
print(nums[0])
# 访问第二列元素（冒号表示获取该纬度的所有数据）
print(nums[:, 1])
# 访问第一行第二列元素
print(nums[0, 1])
# 访问最后一行倒数第二列元素（-1表示最后一个，-2表示倒数第二）
print(nums[-1, -2])
# 最后一行倒数第二列即第四行第二列
print(nums[3, 1])
# 从第一个维度取出第一和第三个元素
print(nums[[0, 2], :])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[ 1  4  7 10]
1
10
10
[[0 1 2]
 [6 7 8]]


In [16]:
# 这是一个三维数组，如果把多维数组看成一维数组的嵌套，第一个维度表示最外层的元素，以此类推，最后一个维度表示多维数组最内层的元素
nums = np.arange(18).reshape(3, 3, 2);
print(nums)

# 每个维度的索引或切片用逗号分隔，切片通过start:stop:step表示
# stop默认值为-1，step默认值为1，默认值可以省略
# 访问第一个维度的第二个及其之后的元素，第二个维度的所有元素，第三位维度的第一个元素
print(nums[1:, :, 0])

# 访问第一个维度的第一个元素，第二个维度的第一和第二元素，第三个维度的最后一个元素
print(nums[0, :2, -1])

# 访问第一个维度的第一个和第二个元素，第三和第四维度的所有元素
# 对于后面的所有维度可以用省略号（三个点）表示
print(nums[:2, ...])
# 上面的写法等同于如下的写法
print(nums[:2, :, :])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[[ 6  8 10]
 [12 14 16]]
[1 3]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [15]:
# 3. 数组的基本操作

import numpy as np
# 生成一个2X2的数组，元素最小值为0，最大值为10
print('-' * 50)
x = np.random.randint(0, 10, (2, 2))
y = np.random.randint(0, 10, (2, 2))

# 使用pprint美化输出
from pprint import pprint
pprint(x)
pprint(y)

# 给每个元素进行加减乘除一个常数
pprint(x + 2)
pprint(x - 2.0)
pprint(x * 0.5)
pprint(x / 0.5)

# 数组的加减乘除（Element-wise，对应运算符作用在两个数组的对应元素上）
pprint(x + y)
pprint(x - y)
pprint(x * y)
# 对于除法，为了防止除数为0，我们给y添加一个微小的常数
pprint(x / (y + 1e-6))

--------------------------------------------------
array([[0, 3],
       [5, 1]])
array([[1, 4],
       [2, 8]])
array([[2, 5],
       [7, 3]])
array([[-2.,  1.],
       [ 3., -1.]])
array([[0. , 1.5],
       [2.5, 0.5]])
array([[ 0.,  6.],
       [10.,  2.]])
array([[1, 7],
       [7, 9]])
array([[-1, -1],
       [ 3, -7]])
array([[ 0, 12],
       [10,  8]])
array([[0.        , 0.74999981],
       [2.49999875, 0.12499998]])


In [18]:
# 向量内积
x = np.array(range(5))
y = np.random.randint(0, 10, (5,))
print(x)
print(y)

# 下面两种方式可以得到相同的结果
print(x.dot(y))
print(np.dot(x, y))

# 矩阵乘法
x = np.random.randint(0, 10, (3, 2))
y = np.random.randint(0, 10, (2, 3))
pprint(x)
pprint(y)
pprint(np.matmul(x, y))

# 行列式
x = np.random.randint(0, 10, (3, 3))
y = np.random.randint(0, 10, (3, 3))
pprint(x)
pprint(y)
pprint(np.linalg.det(x))
pprint(np.linalg.det(y))

# 矩阵逆
pprint(np.linalg.inv(x))

# 转置矩阵
pprint(x.T)

[0 1 2 3 4]
[7 1 4 3 4]
34
34
array([[1, 4],
       [1, 3],
       [5, 6]])
array([[4, 2, 5],
       [6, 6, 4]])
array([[28, 26, 21],
       [22, 20, 17],
       [56, 46, 49]])
array([[9, 2, 5],
       [0, 2, 2],
       [0, 5, 2]])
array([[6, 0, 9],
       [5, 0, 0],
       [3, 8, 4]])
-53.999999999999986
360.00000000000006
array([[ 0.11111111, -0.38888889,  0.11111111],
       [ 0.        , -0.33333333,  0.33333333],
       [ 0.        ,  0.83333333, -0.33333333]])
array([[9, 0, 0],
       [2, 2, 5],
       [5, 2, 2]])


In [22]:
# 数组元素的筛选
import numpy as np
from pprint import pprint
# 随机生成5X5的整数数组
nums = np.random.randint(0, 10, (5, 5))
pprint(nums)
# 使用np.where()方法得到满足条件的索引，where()函数的参数为判别条件，这里选择大于5的元素
indices = np.where(nums > 5)
pprint(indices)
# 输出对应元素值
pprint(nums[indices])

# 上述通过np.where()函数获得满足条件的索引然后输出对应元素这两个步骤可以通过np.extract()函数来实现，extract()函数第一个参数为判别条件，第二参数为多维数组
pprint(np.extract(nums > 5, nums))

# 选择满足判别条件的元素并重新赋值
# 给nums中大于5的元素赋值为5
nums[nums > 5] = 5
pprint(nums)

array([[2, 4, 1, 6, 3],
       [9, 3, 3, 5, 7],
       [3, 3, 6, 9, 5],
       [4, 6, 0, 0, 3],
       [2, 5, 8, 7, 9]])
(array([0, 1, 1, 2, 2, 3, 4, 4, 4]), array([3, 0, 4, 2, 3, 1, 2, 3, 4]))
array([6, 9, 7, 6, 9, 6, 8, 7, 9])
array([6, 9, 7, 6, 9, 6, 8, 7, 9])
array([[2, 4, 1, 5, 3],
       [5, 3, 3, 5, 5],
       [3, 3, 5, 5, 5],
       [4, 5, 0, 0, 3],
       [2, 5, 5, 5, 5]])


In [31]:
# 数组排序函数
import numpy as np
from pprint import pprint

nums = np.random.randint(-2, 10, 10)
pprint(nums)

# np.sort()函数返回输入数组的排序副本
# np.sort(a, axis=-1, kind=None, order=None)有四个参数，a为待排序的多维数组，axis指定排序的维度，kind指定排序算法，order在数组包含多个字段的情况下，指定排序算法使用的字段
pprint(np.sort(nums))

# 当数组为多维的时候，我们可以指定排序的维度
nums = np.random.randint(-2, 10, (4, 4))
pprint(nums)
# 第一个维度表示最外层的元素，以此类推，最后一个维度表示多维数组最内层的元素
pprint(np.sort(nums, 0))
pprint(np.sort(nums, 1))

# np.argsort()函数用于返回排好序以后的多维数组的元素在原始数组中的索引位置
# np.argsort()函数具有和np.sort()函数相同的参数
pprint(np.argsort(nums))

# 多维数组中指定维度的最大值，最小值
# 和np.amax(nums, 0)函数的输出一致
pprint(nums.max(0))  # 第一个维度（列）的最大值
# 和np.amin(nums, 1)函数的输出一致
pprint(nums.min(1))  # 第二个维度（行）的最小值

# 相应的，利用np.argmax()和np.argmin() 方法可以得到最大值和最小值对应的索引，大家可以观察一下这个两个函数输出的索引是不是和max()和min()函数输出的最值相对应
pprint(np.argmax(nums, 0))
pprint(np.argmin(nums, 1))

array([-1,  9,  8,  3,  9,  9,  2,  5,  8,  3])
array([-1,  2,  3,  3,  5,  8,  8,  9,  9,  9])
array([[ 9,  9,  3,  7],
       [ 1,  4,  6,  5],
       [ 9, -2, -1,  3],
       [ 5,  6,  5,  6]])
array([[ 1, -2, -1,  3],
       [ 5,  4,  3,  5],
       [ 9,  6,  5,  6],
       [ 9,  9,  6,  7]])
array([[ 3,  7,  9,  9],
       [ 1,  4,  5,  6],
       [-2, -1,  3,  9],
       [ 5,  5,  6,  6]])
array([[2, 3, 0, 1],
       [0, 1, 3, 2],
       [1, 2, 3, 0],
       [0, 2, 1, 3]])
array([9, 9, 6, 7])
array([ 3,  1, -2,  5])
array([0, 0, 1, 0])
array([2, 0, 1, 0])
