In [3]:
# vstack()和hstack()的用法和示例
import numpy as np
import pandas as pd

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.vstack((x, y))
print(z)
print(z.shape)
print('------')
z = np.hstack((x, y))
print(z)
print(z.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
------
[1 2 3 4 5 6]
(6,)


In [4]:
# vstack()和hstack()的用法和示例
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.vstack((x, y))
print(z)
print(z.shape)
print('------')
z = np.hstack((x, y))
print(z)
print(z.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [5]:
# stack()函数用法示例
data = [np.random.randn(3, 4) for _ in range(10)]
# 沿着不同维度进行合并
print(np.stack(data, axis=0).shape)
print(np.stack(data, axis=1).shape)
print(np.stack(data, axis=2).shape)

(10, 3, 4)
(3, 10, 4)
(3, 4, 10)


In [6]:
# concatenate()函数用法示例
print(np.concatenate(data, axis=0).shape)
print(np.concatenate(data, axis=1).shape)

# 将concatenate()函数和前面的vstack()和hstack()函数进行对比
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.concatenate((x, y), axis=0)
print(z)
print(z.shape)
print('------')
z = np.concatenate((x, y), axis=1)
print(z)
print(z.shape)

(30, 4)
(3, 40)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [2]:
import numpy as np

data = np.random.random((3, 4))
# 新增一个维度
data = data[np.newaxis, ...]
print(data.shape)

# 再新增一个维度
data = data[None, ...]
print(data.shape)

# 减少多余的维度
data = np.squeeze(data)
print(data.shape)

(1, 3, 4)
(1, 1, 3, 4)
(3, 4)


In [8]:
from numpy import ma

data = np.random.randn(3, 4)
print(data)
x = ma.MaskedArray(data, mask=(data < 0))
print(x)
y = ma.MaskedArray(data, mask=(data > 1))
print(y)

# 给x和y求和，其无值部分在结果中均会被掩膜掉
print(x + y)

[[-0.4618663   2.82662789  1.34347775 -0.07336825]
 [ 0.42905222  1.37543576  0.29207739  1.41661034]
 [-0.24030227  1.21224896  0.78048049 -1.3031132 ]]
[[-- 2.8266278870087005 1.3434777470716037 --]
 [0.4290522244591068 1.3754357642899397 0.2920773869823191
  1.4166103421795717]
 [-- 1.2122489612253422 0.7804804866391125 --]]
[[-0.46186629522408007 -- -- -0.07336824583766437]
 [0.4290522244591068 -- 0.2920773869823191 --]
 [-0.24030226842105107 -- 0.7804804866391125 -1.3031131950508745]]
[[-- -- -- --]
 [0.8581044489182136 -- 0.5841547739646382 --]
 [-- -- 1.560960973278225 --]]


In [17]:
%%time
count = 10000
vector = np.random.random((count, count))
for i in range(count):
    for j in range(count):
        vector[i][j] = vector[i][j] ** 2 + 3.14

CPU times: total: 37.4 s
Wall time: 1min


In [18]:
%%time
count = 10000
vector = np.random.random((count, count))
vector = vector ** 2 + 3.14

CPU times: total: 609 ms
Wall time: 1.3 s


In [19]:
# NumPy内置支持的向量化编程函数
data = np.random.randint(0, 9, (10,))
print(data)

# 找到数组中大于5的元素的位置
print(np.where(data > 5))
# 找出数组的中值
print(np.median(data))
# 找出数组的中最小值对应的索引位置
print(np.argmin(data))
# 判断数组是否都大于9
print(np.all(data > 9))

[1 7 7 4 0 5 3 6 0 0]
(array([1, 2, 7], dtype=int64),)
3.5
4
False


In [27]:
# 将自定义函数转化为支持向量化编程的函数
def func(a, b):
    if a > b:
        return a - b
    else:
        return a + b

# 使用np.vectorize()函数将普通函数转化为支持向量化编程的函数
vfunc = np.vectorize(func)

# 随机生成两个二维数组
x = np.random.randint(0, 9, (3, 3))
print(x)
y = np.random.randint(0, 9, (3, 3))
print(y)
# 使用我们自定义的支持向量化的函数
# 注意fun(a, b)函数中a和b的维度要匹配
z = vfunc(x, y)
print(z)
# 参数a或者b如果是一个标量，维度也是匹配的
print(vfunc(x, 3))

[[1 0 2]
 [4 4 1]
 [8 4 5]]
[[8 1 2]
 [3 0 7]
 [3 1 2]]
[[9 1 4]
 [1 4 8]
 [5 3 3]]
[[4 3 5]
 [1 1 4]
 [5 1 2]]


In [28]:
# 随机生成三维的整数数组
data = np.random.randint(0, 9, (2, 3, 4))
print(data)

# 在第二个维度中找最大值
print(np.apply_along_axis(np.max, 1, data))
# 将第一个和第三个维度的数据进行相加
print(np.apply_over_axes(np.sum, data, (0, 2)))

[[[2 2 7 6]
  [4 7 0 4]
  [4 7 3 2]]

 [[4 0 0 7]
  [8 6 3 0]
  [1 3 7 3]]]
[[4 7 7 6]
 [8 6 7 7]]
[[[28]
  [32]
  [30]]]
